// Package coreFirebase
/*
This is the STY-Holdings shared services

NOTES:

	None

COPYRIGHT & WARRANTY:

	Copyright (c) 2022 STY-Holdings, inc
	All rights reserved.

	This software is the confidential and proprietary information of STY-Holdings, Inc.
	Use is subject to license terms.

	Unauthorized copying of this file, via any medium is strictly prohibited.

	Proprietary and confidential

	Written by <Replace with FULL_NAME> / syacko
	STY-Holdings, Inc.
	support@sty-holdings.com
	www.sty-holdings.com

	01-2024
	USA

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
package coreFirebase

const (
	//
	//goland:noinspection ALL
	TEST_FIREBASE_IDTOKEN_VALID   = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjU4ODI0YTI2ZjFlY2Q1NjEyN2U4OWY1YzkwYTg4MDYxMTJhYmU5OWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc2F2dXAtZGV2ZWxvcG1lbnQiLCJhdWQiOiJzYXZ1cC1kZXZlbG9wbWVudCIsImF1dGhfdGltZSI6MTY3ODc1MTE0OCwidXNlcl9pZCI6IkxCSUJiUFZ0WjhUenB0QVp4WEpmbGQxV0xodzIiLCJzdWIiOiJMQklCYlBWdFo4VHpwdEFaeFhKZmxkMVdMaHcyIiwiaWF0IjoxNjc4NzUxMTQ4LCJleHAiOjE2Nzg3NTQ3NDgsImVtYWlsIjoic2NvdHRAeWFja29mYW1pbHkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInNjb3R0QHlhY2tvZmFtaWx5LmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.b34LxeMOK1m9kyoquHZMUt3HLysUq8a1OjnDA41LJNmqE8w0i9oAjeRrg2uKXwaAz2OzbCPDzq9HJkzl9yqf3DN3pk9fXplm-r23cVhQD2_OsZ_WFsjzpfq7atOqprlxFlSS4NLzSdW5ZfD0jIOZWkG81nJ1j5Ku3NPaMGsOw9T5pNtLFbgWAexIa7RE3EUDibzw0HDmLYf-sLXV7vb4u8vugE-9C7eqEqNCJ1WI2l_-l9SuFhXnRQN3Dcwbke4dHOp9rkIdOrQdDHTctcyzmWEPHrN4FtH5a0XcseHs-k1_fzDDyeNIbyNuY0mEqa5qmhIWWrihL2l1dXc_zKQhOA"
	TEST_FIREBASE_IDTOKEN_INVALID = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlYjMxMjdiMjRjZTg2MDJjODEyNDUxZThmZTczZDU4MjkyMDg4N2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc2F2dXAtZGV2ZWxvcG1lbnQiLCJhdWQiOiJzYXZ1cC1kZXZlbG9wbWVudCIsImF1dGhfdGltZSI6MTY3NjQwOTg2MywidXNlcl9pZCI6ImJFQnplaUdyTHhNamd1WHlFMEVRbXliblM2ODIiLCJzdWIiOiJiRUJ6ZWlHckx4TWpndVh5RTBFUW15Ym5TNjgyIiwiaWF0IjoxNjc2NDA5ODYzLCJleHAiOjE2NzY0MTM0NjMsImVtYWlsIjoiZGdvZm1hbkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJkZ29mbWFuQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.xbEqpa5gc2YAgYNvGEOxR3M7blqhTy88aBbwvJrttTibqmE19Cm7ey-0qCGpfi-2Z-umyKApRw31Vif5E8zOI4VFyHuJWCv_dPWBHP_i8VTawW_VLCM76nY5afPC42FoEBi4KjsJrqzfiaKtK6hp9Jbi0Dsth0m-SXZpCbNnwwmGcYN7fst51RdZURzCyFtMlgaJSC1FNWiac1V1He79p5yHJBB8io1AY57aT_GNsnViQ0w0mvLrCNluFV9x40IA1TtpsYNtSMf1rN0WJn5wnCGh0-YcKIE_t6dalq2APGuSD8_i3h4ydalAs7nBWus8LDThY-9RISk4VbGOZZMcHQ"
)
